// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rqyjqhdjqskdvxsicpeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeWpxaGRqcXNrZHZ4c2ljcGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NTY0MDEsImV4cCI6MjA4NDEzMjQwMX0.FcYQeOjWxsAQIjloHZAC-WnIFo-1uFlnx39qm1ulcQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);